// Suggested questions for Ask. Everyday topics the six books speak to directly,
// phrased the way a user would ask. Avoid "is it allowed…" rulings: Ask doesn't give them.
export const SUGGESTED_QUESTIONS = [
  "What did the Prophet ﷺ say about anger?",
  "How should I treat my parents?",
  "What is the reward for patience?",
  "What did the Prophet ﷺ say about smiling?",
  "How should I treat my neighbours?",
  "What is the reward for giving charity?",
  "What did the Prophet ﷺ say about honesty?",
  "How should a guest be treated?",
  "What is the virtue of seeking knowledge?",
  "Why do intentions matter in what we do?",
  "What should I say before I sleep?",
  "What are the manners of eating and drinking?",
  "What did the Prophet ﷺ say about greeting with salam?",
  "What should I say when someone sneezes?",
  "What is the reward for visiting the sick?",
  "How should orphans be cared for?",
  "What did the Prophet ﷺ say about being grateful?",
  "What did the Prophet ﷺ say about backbiting?",
  "What did the Prophet ﷺ say about lying?",
  "What did the Prophet ﷺ say about envy?",
  "Why is modesty important in Islam?",
  "What is the virtue of making wudu?",
  "What is special about Friday?",
  "Which words of remembrance did the Prophet ﷺ love most?",
  "When are supplications most likely to be answered?",
  "What is the reward for reciting the Quran?",
  "What did the Prophet ﷺ say about praying at night?",
  "How did the Prophet ﷺ teach kindness to animals?",
  "What did the Prophet ﷺ say about honest trade?",
  "What did the Prophet ﷺ say about paying off debts?",
  "How should a husband treat his wife?",
  "How did the Prophet ﷺ treat children?",
  "What should be said when someone passes away?",
  "How did the Prophet ﷺ describe Paradise?",
  "Does Allah forgive someone who repents?",
  "What did the Prophet ﷺ say about humility?",
  "What did the Prophet ﷺ warn about arrogance?",
  "What did the Prophet ﷺ say about generosity?",
  "Why should I guard my tongue?",
  "Who did the Prophet ﷺ say has the best character?",
  "What are the rights of one Muslim over another?",
  "What should I say when setting out on a journey?",
  "What is the reward for removing something harmful from the road?",
  "What did the Prophet ﷺ say about contentment?",
  "Which charity keeps rewarding after death?",
  "What is the reward of an accepted Hajj?",
  "What is the reward for fasting in Ramadan?",
  "What is Laylat al-Qadr and how should I seek it?",
  "Who did the Prophet ﷺ call the best of people?",
  "What did the Prophet ﷺ say about keeping family ties?",
];
